export const featuredSongs = [
  {
    id: "lag-ja-gale",
    title: "Lag Jaa Gale",
    artist: "Lata Mangeshkar",
    film: "Woh Kaun Thi?",
    era: "Classic",
    language: "Hindi",
    key: "Gm",
    difficulty: "Intermediate",
    accent: "violet",
    genres: ["Bollywood", "Hindi classics"],
    moods: ["Heart-out", "Romantic", "Retro night", "Easy warm-up"],
  },
  {
    id: "aaj-jaane-ki-zid",
    title: "Aaj Jaane Ki Zid Na Karo",
    artist: "Farida Khanum",
    film: "Ghazal favourite",
    era: "Ghazal",
    language: "Urdu / Hindi",
    key: "Dm",
    difficulty: "Advanced",
    accent: "rose",
    genres: ["Bollywood", "Hindi classics", "Ghazal"],
    moods: ["Heart-out", "Retro night", "High notes"],
  },
  {
    id: "kesariya",
    title: "Kesariya",
    artist: "Arijit Singh",
    film: "Brahmāstra",
    era: "Modern",
    language: "Hindi",
    key: "C",
    difficulty: "Easy",
    accent: "amber",
    genres: ["Bollywood"],
    moods: ["Heart-out", "Romantic", "Easy warm-up"],
  },
  {
    id: "chaleya",
    title: "Chaleya",
    artist: "Arijit Singh & Shilpa Rao",
    film: "Jawan",
    era: "Modern",
    language: "Hindi",
    key: "D",
    difficulty: "Intermediate",
    accent: "blue",
    genres: ["Bollywood", "Duets"],
    moods: ["Romantic", "High notes", "Antakshari"],
  },
  {
    id: "saibo",
    title: "Saibo",
    artist: "Shreya Ghoshal & Tochi Raina",
    film: "Shor in the City",
    era: "2010s",
    language: "Hindi",
    key: "A",
    difficulty: "Easy",
    accent: "mint",
    genres: ["Bollywood", "Duets"],
    moods: ["Romantic", "Easy warm-up", "Antakshari"],
  },
  {
    id: "tujh-mein-rab",
    title: "Tujh Mein Rab Dikhta Hai",
    artist: "Roop Kumar Rathod",
    film: "Rab Ne Bana Di Jodi",
    era: "2000s",
    language: "Hindi",
    key: "F#",
    difficulty: "Intermediate",
    accent: "plum",
    genres: ["Bollywood"],
    moods: ["Heart-out", "Romantic", "High notes", "Antakshari"],
  },
  {
    id: "tum-hi-ho",
    title: "Tum Hi Ho",
    artist: "Arijit Singh",
    film: "Aashiqui 2",
    era: "2010s",
    language: "Hindi",
    difficulty: "Intermediate",
    accent: "violet",
    genres: ["Bollywood"],
    moods: ["Heart-out", "Romantic", "High notes"],
  },
  {
    id: "agar-tum-saath-ho",
    title: "Agar Tum Saath Ho",
    artist: "Alka Yagnik & Arijit Singh",
    film: "Tamasha",
    era: "2010s",
    language: "Hindi",
    difficulty: "Advanced",
    accent: "rose",
    genres: ["Bollywood", "Duets"],
    moods: ["Heart-out", "Romantic", "High notes"],
  },
  {
    id: "abhi-mujh-mein-kahin",
    title: "Abhi Mujh Mein Kahin",
    artist: "Sonu Nigam",
    film: "Agneepath",
    era: "2010s",
    language: "Hindi",
    difficulty: "Advanced",
    accent: "amber",
    genres: ["Bollywood"],
    moods: ["Heart-out", "High notes"],
  },
  {
    id: "pehla-nasha",
    title: "Pehla Nasha",
    artist: "Udit Narayan & Sadhana Sargam",
    film: "Jo Jeeta Wohi Sikandar",
    era: "1990s",
    language: "Hindi",
    difficulty: "Easy",
    accent: "blue",
    genres: ["Bollywood", "Hindi classics", "Duets"],
    moods: ["Romantic", "Retro night", "Easy warm-up"],
  },
  {
    id: "tujhe-dekha-to",
    title: "Tujhe Dekha To",
    artist: "Kumar Sanu & Lata Mangeshkar",
    film: "Dilwale Dulhania Le Jayenge",
    era: "1990s",
    language: "Hindi",
    difficulty: "Intermediate",
    accent: "mint",
    genres: ["Bollywood", "Hindi classics", "Duets"],
    moods: ["Romantic", "Retro night", "Antakshari"],
  },
  {
    id: "kal-ho-naa-ho",
    title: "Kal Ho Naa Ho",
    artist: "Sonu Nigam",
    film: "Kal Ho Naa Ho",
    era: "2000s",
    language: "Hindi",
    difficulty: "Intermediate",
    accent: "plum",
    genres: ["Bollywood"],
    moods: ["Heart-out", "Antakshari", "High notes"],
  },
  {
    id: "iktara",
    title: "Iktara",
    artist: "Kavita Seth",
    film: "Wake Up Sid",
    era: "2000s",
    language: "Hindi",
    difficulty: "Easy",
    accent: "violet",
    genres: ["Bollywood", "Indie India"],
    moods: ["Romantic", "Easy warm-up"],
  },
  {
    id: "kabira",
    title: "Kabira",
    artist: "Rekha Bhardwaj & Tochi Raina",
    film: "Yeh Jawaani Hai Deewani",
    era: "2010s",
    language: "Hindi",
    difficulty: "Intermediate",
    accent: "rose",
    genres: ["Bollywood", "Duets"],
    moods: ["Heart-out", "Antakshari"],
  },
  {
    id: "kun-faya-kun",
    title: "Kun Faya Kun",
    artist: "A.R. Rahman, Javed Ali & Mohit Chauhan",
    film: "Rockstar",
    era: "2010s",
    language: "Urdu / Hindi",
    difficulty: "Advanced",
    accent: "amber",
    genres: ["Bollywood", "Ghazal"],
    moods: ["Heart-out", "High notes"],
  },
  {
    id: "o-re-piya",
    title: "O Re Piya",
    artist: "Rahat Fateh Ali Khan",
    film: "Aaja Nachle",
    era: "2000s",
    language: "Hindi",
    difficulty: "Advanced",
    accent: "blue",
    genres: ["Bollywood", "Ghazal"],
    moods: ["Heart-out", "Romantic", "High notes"],
  },
  {
    id: "zara-zara",
    title: "Zara Zara",
    artist: "Bombay Jayashri",
    film: "Rehnaa Hai Terre Dil Mein",
    era: "2000s",
    language: "Hindi",
    difficulty: "Intermediate",
    accent: "mint",
    genres: ["Bollywood"],
    moods: ["Romantic", "Easy warm-up", "Antakshari"],
  },
  {
    id: "channa-mereya",
    title: "Channa Mereya",
    artist: "Arijit Singh",
    film: "Ae Dil Hai Mushkil",
    era: "2010s",
    language: "Hindi",
    difficulty: "Advanced",
    accent: "plum",
    genres: ["Bollywood"],
    moods: ["Heart-out", "High notes", "Antakshari"],
  },
  {
    id: "phir-le-aya-dil",
    title: "Phir Le Aya Dil",
    artist: "Arijit Singh",
    film: "Barfi!",
    era: "2010s",
    language: "Urdu / Hindi",
    difficulty: "Intermediate",
    accent: "violet",
    genres: ["Bollywood", "Ghazal"],
    moods: ["Heart-out", "Romantic"],
  },
  {
    id: "dil-diyan-gallan",
    title: "Dil Diyan Gallan",
    artist: "Atif Aslam",
    film: "Tiger Zinda Hai",
    era: "2010s",
    language: "Punjabi",
    difficulty: "Easy",
    accent: "rose",
    genres: ["Bollywood", "Punjabi"],
    moods: ["Romantic", "Easy warm-up"],
  },
  {
    id: "pani-da-rang",
    title: "Pani Da Rang",
    artist: "Ayushmann Khurrana",
    film: "Vicky Donor",
    era: "2010s",
    language: "Punjabi",
    difficulty: "Easy",
    accent: "amber",
    genres: ["Bollywood", "Punjabi", "Indie India"],
    moods: ["Romantic", "Easy warm-up"],
  },
  {
    id: "pasoori",
    title: "Pasoori",
    artist: "Ali Sethi & Shae Gill",
    film: "Coke Studio Pakistan",
    era: "2020s",
    language: "Punjabi",
    difficulty: "Intermediate",
    accent: "blue",
    genres: ["Punjabi", "Indie India", "Duets"],
    moods: ["Heart-out", "Antakshari"],
  },
  {
    id: "nenjukkul-peidhidum",
    title: "Nenjukkul Peidhidum",
    artist: "Hariharan, Devan Ekambaram & V.V. Prassanna",
    film: "Vaaranam Aayiram",
    era: "2000s",
    language: "Tamil",
    difficulty: "Intermediate",
    accent: "mint",
    genres: ["Tamil", "Duets"],
    moods: ["Romantic", "Easy warm-up"],
  },
  {
    id: "inkem-inkem",
    title: "Inkem Inkem Inkem Kaavaale",
    artist: "Sid Sriram",
    film: "Geetha Govindam",
    era: "2010s",
    language: "Telugu",
    difficulty: "Intermediate",
    accent: "plum",
    genres: ["Telugu"],
    moods: ["Romantic", "High notes"],
  },
  {
    id: "ek-ladki-ko-dekha",
    title: "Ek Ladki Ko Dekha",
    artist: "Kumar Sanu",
    film: "1942: A Love Story",
    era: "1990s",
    language: "Hindi",
    difficulty: "Easy",
    accent: "violet",
    genres: ["Bollywood", "Hindi classics"],
    moods: ["Romantic", "Retro night", "Easy warm-up"],
  },
  {
    id: "humein-tumse-pyaar-kitna",
    title: "Humein Tumse Pyaar Kitna",
    artist: "Kishore Kumar",
    film: "Kudrat",
    era: "Classic",
    language: "Hindi",
    difficulty: "Intermediate",
    accent: "rose",
    genres: ["Bollywood", "Hindi classics"],
    moods: ["Heart-out", "Retro night", "Antakshari"],
  },
  {
    id: "aap-ki-aankhon-mein-kuch",
    title: "Aap Ki Aankhon Mein Kuch",
    artist: "Kishore Kumar & Lata Mangeshkar",
    film: "Ghar",
    era: "Classic",
    language: "Hindi",
    difficulty: "Easy",
    accent: "amber",
    genres: ["Bollywood", "Hindi classics", "Duets"],
    moods: ["Romantic", "Retro night", "Easy warm-up"],
  },
  {
    id: "kya-mujhe-pyaar-hai",
    title: "Kya Mujhe Pyaar Hai",
    artist: "KK",
    film: "Woh Lamhe",
    era: "2000s",
    language: "Hindi",
    difficulty: "Intermediate",
    accent: "blue",
    genres: ["Bollywood"],
    moods: ["Romantic", "Antakshari", "High notes"],
  },
  {
    id: "ajab-si",
    title: "Ajab Si",
    artist: "KK",
    film: "Om Shanti Om",
    era: "2000s",
    language: "Hindi",
    difficulty: "Intermediate",
    accent: "mint",
    genres: ["Bollywood"],
    moods: ["Romantic", "Easy warm-up"],
  },
  {
    id: "tere-bina",
    title: "Tere Bina",
    artist: "A.R. Rahman & Chinmayi",
    film: "Guru",
    era: "2000s",
    language: "Hindi",
    difficulty: "Advanced",
    accent: "plum",
    genres: ["Bollywood", "Duets"],
    moods: ["Romantic", "Heart-out", "High notes"],
  },
  {
    id: "main-agar-kahoon",
    title: "Main Agar Kahoon",
    artist: "Sonu Nigam & Shreya Ghoshal",
    film: "Om Shanti Om",
    era: "2000s",
    language: "Hindi",
    difficulty: "Intermediate",
    accent: "violet",
    genres: ["Bollywood", "Duets"],
    moods: ["Romantic", "Antakshari"],
  },
  {
    id: "jashn-e-bahaaraa",
    title: "Jashn-E-Bahaaraa",
    artist: "Javed Ali",
    film: "Jodhaa Akbar",
    era: "2000s",
    language: "Urdu / Hindi",
    difficulty: "Intermediate",
    accent: "rose",
    genres: ["Bollywood", "Ghazal"],
    moods: ["Romantic", "Easy warm-up"],
  },
  {
    id: "hawayein",
    title: "Hawayein",
    artist: "Arijit Singh",
    film: "Jab Harry Met Sejal",
    era: "2010s",
    language: "Hindi",
    difficulty: "Intermediate",
    accent: "amber",
    genres: ["Bollywood"],
    moods: ["Romantic", "Heart-out"],
  },
  {
    id: "apna-bana-le",
    title: "Apna Bana Le",
    artist: "Arijit Singh",
    film: "Bhediya",
    era: "2020s",
    language: "Hindi",
    difficulty: "Easy",
    accent: "blue",
    genres: ["Bollywood"],
    moods: ["Romantic", "Easy warm-up"],
  },
  {
    id: "ranjha",
    title: "Ranjha",
    artist: "B Praak & Jasleen Royal",
    film: "Shershaah",
    era: "2020s",
    language: "Punjabi",
    difficulty: "Intermediate",
    accent: "mint",
    genres: ["Bollywood", "Punjabi", "Duets"],
    moods: ["Heart-out", "Romantic"],
  },
  {
    id: "ve-kamleya",
    title: "Ve Kamleya",
    artist: "Arijit Singh & Shreya Ghoshal",
    film: "Rocky Aur Rani Kii Prem Kahaani",
    era: "2020s",
    language: "Hindi",
    difficulty: "Advanced",
    accent: "plum",
    genres: ["Bollywood", "Duets"],
    moods: ["Heart-out", "High notes"],
  },
];

export const genres = [
  "Bollywood",
  "Hindi classics",
  "Ghazal",
  "Indie India",
  "Punjabi",
  "Tamil",
  "Telugu",
  "Duets",
];

export const moods = [
  "Heart-out",
  "Romantic",
  "Retro night",
  "Antakshari",
  "High notes",
  "Easy warm-up",
];

export const demoLyrics = [
  "सुरों में चलो",
  "दिल से गाओ",
  "हर धड़कन को आज सुनाओ",
  "अपनी आवाज़ को आसमान तक ले जाओ",
].join("\n");

export const studioFeatures = [
  {
    id: "lyrics",
    title: "Bilingual lyric sync",
    description: "Sing in Devanagari or switch to an easy Roman-Hindi reading view.",
  },
  {
    id: "loop",
    title: "Precision practice loop",
    description: "Mark A and B around a difficult phrase and repeat it until it lands.",
  },
  {
    id: "record",
    title: "Private local recording",
    description: "Capture your mic in the browser, review the take, and download it locally.",
  },
  {
    id: "coach",
    title: "Live voice coach",
    description: "Watch input energy, stay consistent, and receive a take score after recording.",
  },
];
